(() => {
  const path = location.pathname.split('/').pop() || 'dashboard.html';
  const data = window.QueueSmartData;
  const isPublic = ['login.html', 'register.html', 'join-queue.html', 'queue-status.html'].includes(path);
  const isAuthForm = path === 'login.html' || path === 'register.html';
  document.body.classList.toggle('auth-page', isAuthForm);
  const admin = path === 'admin-dashboard.html' || path === 'service-management.html' || path === 'queue-management.html';
  const nav = admin
    ? [['admin-dashboard.html','Admin dashboard','⌂'],['service-management.html','Services','◇'],['queue-management.html','Queue management','≡'],['history.html','History','◷']]
    : [['dashboard.html','My dashboard','⌂'],['join-queue.html','Join a queue','＋'],['queue-status.html','Queue status','◉'],['history.html','History','◷']];
  const defaultTitles = {'dashboard.html':'My dashboard','admin-dashboard.html':'Admin dashboard','queue-management.html':'Queue management','service-management.html':'Service management','history.html':'Queue history','join-queue.html':'Join a queue','queue-status.html':'Queue status','login.html':'Sign in','register.html':'Create account'};
  const title = document.body.dataset.title || defaultTitles[path] || 'QueueSmart';
  const app = document.querySelector('[data-app-shell]');
  if (!app) return;
  app.innerHTML = `<aside class="sidebar"><a class="brand" href="${admin?'admin-dashboard.html':'dashboard.html'}"><span class="brand-mark">Q</span><span>Queue<span class="brand-light">Smart</span></span></a><div class="side-label">${admin?'ADMINISTRATION':'YOUR QUEUES'}</div><nav>${nav.map(([href,label,icon])=>`<a class="nav-link ${path===href?'active':''}" href="${href}"><span class="nav-icon">${icon}</span>${label}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="help-card"><span class="help-icon">?</span><strong>Need a hand?</strong><p>Get help with your workspace.</p><a href="#" data-toast="Help center coming soon">Visit help center →</a></div><a class="profile" href="login.html"><span class="avatar">JL</span><span><strong>Jordan Lee</strong><small>${admin?'Administrator':'QueueSmart user'}</small></span><span class="profile-more">···</span></a></div></aside><main class="main"><header class="topbar"><a class="mobile-brand" href="${admin?'admin-dashboard.html':'dashboard.html'}"><span class="brand-mark">Q</span> QueueSmart</a><div class="auth-header-copy"><div class="eyebrow">QUEUESMART · CUSTOMER PORTAL</div><h1>${title}</h1></div><div class="breadcrumbs">${admin?'Administration':'My workspace'} <span>/</span> <strong>${title}</strong></div><div class="top-actions"><span class="live-indicator"><i></i> Demo workspace</span><button class="icon-button" aria-label="Notifications" data-toast="You’re all caught up">♧<b></b></button><span class="avatar small-avatar">JL</span></div></header><section class="page-content"><div class="page-heading"><div><div class="eyebrow">QUEUESMART · ${admin?'ADMIN':'CUSTOMER'} PORTAL</div><h1>${title}</h1><p>${document.body.dataset.subtitle || 'Manage your queues and services.'}</p></div><div class="heading-actions">${path==='queue-management.html'?'<button class="button button-primary" data-action="serve-next">Serve next →</button>':''}</div></div><div id="page-content"></div></section></main><div class="toast" role="status" aria-live="polite"></div>`;
  const root = document.querySelector('#page-content');
  const badge = status => `<span class="badge ${status.toLowerCase()}"><i></i>${status}</span>`;
  const tickets = () => data.tickets.map((t,i)=>`<tr><td><strong class="ticket-id">${t.number}</strong></td><td>${t.customer}</td><td>${t.service}</td><td class="muted">${t.joined}</td><td>${badge(t.status)}</td>${admin?`<td class="row-actions"><button class="mini-button" data-action="up" data-index="${i}" aria-label="Move up">↑</button><button class="mini-button" data-action="down" data-index="${i}" aria-label="Move down">↓</button><button class="mini-button" data-action="remove" data-index="${i}" aria-label="Remove ticket">×</button></td>`:''}</tr>`).join('');
  const table = (actions=false) => `<div class="panel"><div class="panel-heading"><div><h2>${actions?'Selected service queue':'Queue history'}</h2><p>${actions?'Reorder or remove customers, or serve the next person.':'Recent visits and outcomes'}</p></div>${actions?`<select id="service-filter" aria-label="Filter by service"><option value="">All services</option>${data.services.map(s=>`<option>${s.name}</option>`).join('')}</select>`:''}</div><div class="table-wrap"><table><thead><tr><th>TICKET</th><th>CUSTOMER</th><th>SERVICE</th><th>JOINED</th><th>STATUS</th>${actions?'<th>ACTIONS</th>':''}</tr></thead><tbody>${tickets()}</tbody></table></div></div>`;
  const serviceList = (manage=false) => `<div class="service-grid">${data.services.map((s,i)=>`<article class="service-card"><div class="service-card-top"><span class="service-symbol symbol-${i%3}">${['◈','＄','⌘'][i%3]}</span>${badge(s.status||'Open')}</div><h3>${s.name}</h3><p>${s.description}</p><div class="service-metrics"><span><strong>${s.wait} min</strong><small>Expected wait</small></span><span><strong>${data.tickets.filter(t=>t.service===s.name&&t.status==='Waiting').length+2} people</strong><small>In this queue</small></span></div>${manage?`<div class="card-actions"><button class="button button-secondary" data-action="edit-service" data-index="${i}">Edit</button><button class="button button-secondary" data-action="toggle-service" data-index="${i}">${s.status==='Open'?'Close queue':'Open queue'}</button></div>`:`<a class="button button-primary full-width" href="join-queue.html?service=${encodeURIComponent(s.id)}">Join queue →</a>`}</article>`).join('')}${manage?'':'<a class="add-service" href="join-queue.html"><span>＋</span><strong>Choose a service</strong><small>See all available queues</small></a>'}</div>`;
  let markup='';
  if(path==='login.html'||path==='register.html') markup=`<div class="form-card"><div class="eyebrow">QUEUESMART ACCOUNT</div><h2>${path==='login.html'?'Welcome back':'Create your account'}</h2><p>${path==='login.html'?'Sign in to manage your queues.':'Register to join and track queues.'}</p><form id="auth-form" novalidate>${path==='register.html'?'<label>Full name<input name="name" autocomplete="name" required maxlength="100"></label>':''}<label>Email<input name="email" type="email" autocomplete="email" placeholder="you@example.com" required></label><label>Password<input name="password" type="password" autocomplete="current-password" minlength="8" required></label><div class="form-message" aria-live="polite"></div><button class="button button-primary full-width">${path==='login.html'?'Sign in':'Create account'} →</button></form><div class="auth-divider"><span>or continue with</span></div><button type="button" id="google-signin-fallback" class="google-fallback"><svg viewBox="0 0 48 48" aria-hidden="true"><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.92c-.58 2.96-2.26 5.48-4.74 7.18l7.3 5.66c4.27-3.94 6.73-9.74 6.73-17.31z"/><path fill="#FBBC05" d="M10.53 28.59A14.4 14.4 0 0 1 9.75 24c0-1.59.27-3.13.76-4.59l-7.98-6.19A23.9 23.9 0 0 0 0 24c0 3.87.93 7.53 2.56 10.78l7.97-6.19z"/><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.9-5.79l-7.3-5.66c-2.02 1.35-4.6 2.15-8.6 2.15-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 43.62 14.62 48 24 48z"/></svg><span>Continue with Google</span></button><div id="google-signin-button"></div><div class="form-switch">${path==='login.html'?'New to QueueSmart? <a href="register.html">Create an account</a>':'Already registered? <a href="login.html">Sign in</a>'}</div></div>`;
  else if(path==='join-queue.html') markup=`<div class="form-card"><div class="eyebrow">CUSTOMER PORTAL</div><h2>Join a queue</h2><p>Choose an active service and save your place.</p><form id="join-form" novalidate><label>Your name<input name="name" autocomplete="name" maxlength="100" required placeholder="e.g. Jordan Lee"></label><label>Email address<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Service<select name="service" required><option value="">Select a service</option>${data.services.filter(s=>s.status==='Open').map(s=>`<option value="${s.id}">${s.name} · about ${s.wait} min</option>`).join('')}</select></label><div class="wait-preview" id="wait-preview">Select a service to see the estimated wait.</div><div class="form-message" aria-live="polite"></div><button class="button button-primary full-width">Join queue →</button></form></div>`;
  else if(path==='queue-status.html') { const current=JSON.parse(sessionStorage.getItem('queueTicket')||'null')||data.tickets.find(t=>t.status==='Waiting')||{number:'A024',service:'General Inquiry',status:'Waiting',wait:'12 min'}; markup=`<div class="status-card"><span class="status-check">✓</span><div class="eyebrow">QUEUE UPDATE</div><h2>Ticket <span class="ticket-id" id="status-ticket">${current.number}</span></h2><p id="status-copy">You’re in line for ${current.service}. We’ll notify you when it’s your turn.</p><div class="wait-highlight"><strong id="status-wait">~${current.wait}</strong><span>Estimated wait time</span></div><div class="queue-position"><span>Current status</span><strong id="status-state">${current.status}</strong></div><div class="queue-position"><span>People ahead of you</span><strong>${Math.max(0,data.tickets.filter(t=>t.status==='Waiting').length-1)}</strong></div><button class="button button-secondary full-width" data-action="advance-status">Simulate queue update</button><button class="button button-secondary full-width" data-action="leave-queue">Leave queue</button></div>`; }
  else if(path==='service-management.html') markup=`<div class="section-intro"><div><h2>Active services</h2><p>Create, update, and open or close queues.</p></div><button class="button button-primary" data-action="new-service">＋ Add service</button></div><div id="service-form-slot"></div>${serviceList(true)}`;
  else if(path==='queue-management.html') markup=`<div class="toolbar"><div class="tabs"><span class="tab active">Live queue</span></div><label class="search-box">⌕ <input id="ticket-search" placeholder="Search tickets..." aria-label="Search tickets"></label></div>${table(true)}`;
  else if(path==='history.html') markup=table(false);
  else if(path==='admin-dashboard.html') markup=`<div class="section-intro"><div><h2>Service queues</h2><p>Current queue lengths and availability.</p></div><a class="button button-secondary" href="service-management.html">Manage services →</a></div>${serviceList(true)}<div class="notification-card"><strong>Notifications</strong><span>Queue updates are shown here in this demo.</span><button class="button button-secondary" data-toast="No new queue notifications">View updates</button></div>`;
  else markup=`<div class="user-welcome"><div><h2>Welcome back, Jordan</h2><p>Here’s your queue activity today.</p></div><a class="button button-primary" href="join-queue.html">＋ Join a queue</a></div><div class="notification-card"><strong>Notifications <span class="notification-dot"></span></strong><span>You’ll see queue updates and status changes here.</span><button class="button button-secondary" data-toast="You’re all caught up">View notifications</button></div><div class="section-intro"><div><h2>Available services</h2><p>Join a service queue and track your wait.</p></div></div>${serviceList(false)}<div class="panel recent-history"><div class="panel-heading"><div><h2>Your recent queues</h2><p>Past and current visits</p></div><a href="history.html" class="text-link">View history →</a></div><div class="table-wrap"><table><thead><tr><th>TICKET</th><th>SERVICE</th><th>JOINED</th><th>STATUS</th></tr></thead><tbody>${data.tickets.slice(0,3).map(t=>`<tr><td class="ticket-id">${t.number}</td><td>${t.service}</td><td>${t.joined}</td><td>${badge(t.status)}</td></tr>`).join('')}</tbody></table></div></div>`;
  root.innerHTML=markup;
  const toast = message => {const box=document.querySelector('.toast');box.textContent=message;box.classList.add('show');clearTimeout(window.queueToastTimer);window.queueToastTimer=setTimeout(()=>box.classList.remove('show'),2500);};
  document.addEventListener('click',event=>{
    const target=event.target.closest('[data-toast],[data-action]'); if(!target)return;
    if(target.dataset.toast){event.preventDefault();toast(target.dataset.toast);return;}
    const index=Number(target.dataset.index), action=target.dataset.action;
    if(action==='toggle-service'){const s=data.services[index];s.status=s.status==='Open'?'Closed':'Open';data.save?.();root.innerHTML=path==='admin-dashboard.html'?`${serviceList(true)}<div class="notification-card"><strong>Notifications</strong><span>Queue updates are shown here in this demo.</span></div>`:`${document.querySelector('.section-intro')?.outerHTML||''}${serviceList(true)}`;toast(`${s.name} queue ${s.status.toLowerCase()}.`);}
    if(action==='remove'){data.tickets.splice(index,1);data.save?.();root.innerHTML=`${table(true)}`;toast('Ticket removed from the demo queue.');}
    if(action==='up'||action==='down'){const next=index+(action==='up'?-1:1);if(next>=0&&next<data.tickets.length)[data.tickets[index],data.tickets[next]]=[data.tickets[next],data.tickets[index]];data.save?.();root.innerHTML=`<div class="toolbar"><label class="search-box">⌕ <input id="ticket-search" placeholder="Search tickets..."></label></div>${table(true)}`;}
    if(action==='serve-next'){const next=data.tickets.find(t=>t.status==='Waiting');if(next){next.status='Serving';data.save?.();toast(`${next.number} is now being served.`);root.innerHTML=`<div class="toolbar"><label class="search-box">⌕ <input id="ticket-search" placeholder="Search tickets..."></label></div>${table(true)}`;}else toast('No customers are waiting.');}
    if(action==='advance-status'){const states=['Waiting','Almost ready','Served'];const node=document.querySelector('#status-state');const current=node?.textContent||'Waiting';const next=states[(states.indexOf(current)+1)%states.length];if(node)node.textContent=next;const copy=document.querySelector('#status-copy');if(copy)copy.textContent=next==='Served'?'You have been served. Thanks for using QueueSmart!':next==='Almost ready'?'You’re almost up. Please get ready.':'You’re in line. We’ll notify you when it’s your turn.';toast(`Queue status updated: ${next}.`);}
    if(action==='leave-queue'){const ticket=JSON.parse(sessionStorage.getItem('queueTicket')||'null');if(ticket){data.tickets=data.tickets.filter(t=>t.number!==ticket.number);data.save?.();sessionStorage.removeItem('queueTicket');}toast('You left the queue.');location.href='dashboard.html';}
    if(action==='new-service'||action==='edit-service') showServiceForm(action==='edit-service'?index:null);
  });
  function showServiceForm(index=null){const existing=index===null?null:data.services[index];const slot=document.querySelector('#service-form-slot');if(!slot)return;slot.innerHTML=`<div class="form-card service-editor"><h2>${existing?'Edit service':'Create service'}</h2><form id="service-form" novalidate><label>Service name<input name="name" maxlength="100" required value="${existing?.name||''}"></label><label>Description<textarea name="description" required rows="3">${existing?.description||''}</textarea></label><label>Expected duration (minutes)<input name="duration" type="number" min="1" required value="${existing?.wait||''}"></label><label>Priority level<select name="priority" required><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><div class="form-message" aria-live="polite"></div><button class="button button-primary">${existing?'Save changes':'Create service'}</button><button type="button" class="button button-secondary" data-action="cancel-form">Cancel</button></form></div>`;slot.scrollIntoView({behavior:'smooth',block:'center'});slot.querySelector('#service-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const item={id:existing?.id||`S-${String(Date.now()).slice(-4)}`,name:f.elements.name.value.trim(),description:f.elements.description.value.trim(),wait:Number(f.elements.duration.value),priority:f.elements.priority.value,status:existing?.status||'Open'};if(existing)data.services[index]=item;else data.services.push(item);data.save?.();location.reload();});}
  document.addEventListener('click',event=>{if(event.target.closest('[data-action="cancel-form"]'))document.querySelector('#service-form-slot').innerHTML='';});
  document.querySelector('#join-form')?.addEventListener('change',e=>{if(e.target.name==='service'){const s=data.services.find(item=>item.id===e.target.value);document.querySelector('#wait-preview').textContent=s?`Estimated wait: about ${s.wait} minutes.`:'Select a service to see the estimated wait.';}});
  document.querySelector('#join-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const message=f.querySelector('.form-message');try{const ticket=await window.QueueSmartApi.joinQueue(f.elements.service.value,f.elements.name.value.trim());sessionStorage.setItem('queueTicket',JSON.stringify(ticket));location.href='queue-status.html';}catch(error){message.textContent=error.message;}});
  if (isPublic && (path==='login.html'||path==='register.html')) { const googleScript=document.createElement('script'); googleScript.src='js/config.js'; googleScript.onload=()=>{const loader=document.createElement('script');loader.src='js/google-auth.js';document.body.append(loader);}; document.body.append(googleScript); }
  document.querySelector('#auth-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;f.querySelector('.form-message').textContent='Form is valid. Account access is a front-end demo.';});
  document.querySelector('#ticket-search')?.addEventListener('input',e=>{const query=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query));});
})();
